/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Form;
import Controller.ControllerKembali;
import Controller.ControllerPinjam;
import Model.ModelKembali;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Nanda
 */
public class FormKembali extends javax.swing.JFrame {
    
    ControllerKembali controller = new ControllerKembali();
ControllerPinjam cp = new ControllerPinjam();

DefaultTableModel model = new DefaultTableModel();
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormKembali.class.getName());

    /**
     * Creates new form ControllerKembali
     */
    public FormKembali() {
    initComponents();

    model.addColumn("ID Kembali");
    model.addColumn("Peminjam");
    model.addColumn("Barang");
    model.addColumn("Tanggal");

    tbkembali.setModel(model);

    tampilkanData();
    tampilComboPinjam();

    tfidcustomer.setEnabled(false);
}
    
    private void tampilkanData() {
    controller.tampil(model);
}
    
    private void resetForm() {

    tfidcustomer.setText("");
    tftanggal.setText("");

    copinjam.setSelectedIndex(0);
}
    
    private void tampilComboPinjam() {

    try {

        copinjam.removeAllItems();

        ResultSet rs =
        cp.cn.createStatement().executeQuery(
        "SELECT id_pinjam,peminjam FROM tb_pinjam");

        while(rs.next()){

            copinjam.addItem(
                rs.getString("id_pinjam")
                +" - "+
                rs.getString("peminjam")
            );
        }

    } catch(Exception e){

        JOptionPane.showMessageDialog(
                null,
                e.getMessage()
        );
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbkembali = new javax.swing.JTable();
        bttambah = new javax.swing.JButton();
        btedit = new javax.swing.JButton();
        bthapus = new javax.swing.JButton();
        btreset = new javax.swing.JButton();
        btkembali = new javax.swing.JButton();
        tftanggal = new javax.swing.JTextField();
        tfidcustomer = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        copinjam = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tbkembali.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID Kembali", "Tanggal", "ID Pinjam"
            }
        ));
        tbkembali.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbkembaliMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbkembali);

        bttambah.setText("Tambah");
        bttambah.addActionListener(this::bttambahActionPerformed);

        btedit.setText("Edit");
        btedit.addActionListener(this::bteditActionPerformed);

        bthapus.setText("Hapus");
        bthapus.addActionListener(this::bthapusActionPerformed);

        btreset.setText("Reset");
        btreset.addActionListener(this::btresetActionPerformed);

        btkembali.setText("Kembali");
        btkembali.addActionListener(this::btkembaliActionPerformed);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("FORM KEMBALI");

        jLabel2.setText("ID Kembali");

        jLabel3.setText("Tanggal");

        jLabel4.setText("ID Pinjam");

        copinjam.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(243, 243, 243)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel4))
                                        .addGap(28, 28, 28)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(tfidcustomer, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)
                                            .addComponent(tftanggal)
                                            .addComponent(copinjam, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(bttambah)
                                        .addGap(18, 18, 18)
                                        .addComponent(btedit)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(bthapus)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btreset)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btkembali)))))
                        .addGap(17, 17, 17))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 574, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfidcustomer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tftanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(copinjam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bttambah)
                    .addComponent(btedit)
                    .addComponent(bthapus)
                    .addComponent(btreset)
                    .addComponent(btkembali))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tbkembaliMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbkembaliMouseClicked
        int baris = tbkembali.getSelectedRow();

    if(baris > -1){

        tfidcustomer.setText(
                tbkembali.getValueAt(baris,0).toString()
        );

        tftanggal.setText(
                tbkembali.getValueAt(baris,3).toString()
        );
    }       // TODO add your handling code here:
    }//GEN-LAST:event_tbkembaliMouseClicked

    private void bttambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttambahActionPerformed
       
    if(tftanggal.getText().trim().isEmpty()){

        JOptionPane.showMessageDialog(
                null,
                "Tanggal tidak boleh kosong!"
        );

        return;
    }

    ModelKembali mk = new ModelKembali();

    mk.setTanggal(
            tftanggal.getText()
    );

    int idPinjam = Integer.parseInt(
            copinjam.getSelectedItem()
            .toString()
            .split(" - ")[0]
    );

    mk.setId_pinjam(idPinjam);

    controller.tambah(mk);

    tampilkanData();
    resetForm();      // TODO add your handling code here:
    }//GEN-LAST:event_bttambahActionPerformed

    private void bteditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bteditActionPerformed
    
    if(tfidcustomer.getText().isEmpty()){

        JOptionPane.showMessageDialog(
                null,
                "Pilih data terlebih dahulu!"
        );

        return;
    }

    ModelKembali mk = new ModelKembali();

    mk.setId_kembali(
            Integer.parseInt(
                    tfidcustomer.getText()
            )
    );

    mk.setTanggal(
            tftanggal.getText()
    );

    int idPinjam = Integer.parseInt(
            copinjam.getSelectedItem()
            .toString()
            .split(" - ")[0]
    );

    mk.setId_pinjam(idPinjam);

    controller.edit(mk);

    tampilkanData();
    resetForm(); // TODO add your handling code here:
    }//GEN-LAST:event_bteditActionPerformed

    private void bthapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bthapusActionPerformed
      
    if(tfidcustomer.getText().isEmpty()){

        JOptionPane.showMessageDialog(
                null,
                "Pilih data terlebih dahulu!"
        );

        return;
    }

    int jawab = JOptionPane.showConfirmDialog(
            null,
            "Yakin hapus data?",
            "Konfirmasi",
            JOptionPane.YES_NO_OPTION
    );

    if(jawab == JOptionPane.YES_OPTION){

        controller.hapus(
                tfidcustomer.getText()
        );

        tampilkanData();
        resetForm();
    }      // TODO add your handling code here:
    }//GEN-LAST:event_bthapusActionPerformed

    private void btresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btresetActionPerformed
        resetForm();        // TODO add your handling code here:
    }//GEN-LAST:event_btresetActionPerformed

    private void btkembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btkembaliActionPerformed
        int konfirmasi = JOptionPane.showConfirmDialog(null,
            "Yakin ingin keluar?", "Konfirmasi",
            JOptionPane.YES_NO_OPTION);

        if (konfirmasi == JOptionPane.YES_OPTION) {
            new FormUtama().setVisible(true);
            this.dispose();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_btkembaliActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FormKembali().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btedit;
    private javax.swing.JButton bthapus;
    private javax.swing.JButton btkembali;
    private javax.swing.JButton btreset;
    private javax.swing.JButton bttambah;
    private javax.swing.JComboBox<String> copinjam;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbkembali;
    private javax.swing.JTextField tfidcustomer;
    private javax.swing.JTextField tftanggal;
    // End of variables declaration//GEN-END:variables
}
