/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Form;

import Controller.ControllerPinjam;
import Model.ModelPinjam;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Nanda
 */
public class FormPinjam extends javax.swing.JFrame {
    
    ControllerPinjam controller = new ControllerPinjam();
DefaultTableModel model = new DefaultTableModel();
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormPinjam.class.getName());

    /**
     * Creates new form FormPinjam
     */
    public FormPinjam() {
    initComponents();

    model.addColumn("ID Pinjam");
    model.addColumn("Peminjam");
    model.addColumn("Tanggal");
    model.addColumn("Barang");

    tbpinjam.setModel(model);

    tampilkanData();

    loadComboBarang();

    tfid.setEnabled(false);
}
    
    private void tampilkanData() {
    controller.tampil(model);
}

private void resetForm() {
    tfid.setText("");
    tfpeminjam.setText("");
    tftanggal.setText("");

    if(cobarang.getItemCount() > 0){
        cobarang.setSelectedIndex(0);
    }
}

    private void loadComboBarang() {

      try {

        cobarang.removeAllItems();

        ResultSet rs = controller.tampilBarang();

        while(rs.next()) {

            cobarang.addItem(
                rs.getString("id_barang")
                + " - " +
                rs.getString("nama_barang")
            );
        }

    } catch(Exception e) {

        JOptionPane.showMessageDialog(
                null,
                e.getMessage()
        );
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbpinjam = new javax.swing.JTable();
        bttambah = new javax.swing.JButton();
        btedit = new javax.swing.JButton();
        bthapus = new javax.swing.JButton();
        btreset = new javax.swing.JButton();
        btkembali = new javax.swing.JButton();
        tftanggal = new javax.swing.JTextField();
        tfpeminjam = new javax.swing.JTextField();
        tfid = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cobarang = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tbpinjam.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID Pinjam", "Peminjam", "Tanggal", "ID Barang"
            }
        ));
        tbpinjam.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbpinjamMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbpinjam);

        bttambah.setText("Tambah");
        bttambah.addActionListener(this::bttambahActionPerformed);

        btedit.setText("Edit");
        btedit.addActionListener(this::bteditActionPerformed);

        bthapus.setText("Hapus");
        bthapus.addActionListener(this::bthapusActionPerformed);

        btreset.setText("Reset");
        btreset.addActionListener(this::btresetActionPerformed);

        btkembali.setText("Kembali");
        btkembali.addActionListener(this::btkembaliActionPerformed);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("FORM PINJAM");

        jLabel2.setText("ID Pinjam");

        jLabel3.setText("Peminjam");

        jLabel4.setText("Tanggal");

        jLabel5.setText("ID Barang");

        cobarang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(243, 243, 243)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel5))
                                        .addGap(28, 28, 28)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(tfid, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)
                                            .addComponent(tfpeminjam)
                                            .addComponent(tftanggal)
                                            .addComponent(cobarang, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(bttambah)
                                        .addGap(18, 18, 18)
                                        .addComponent(btedit)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(bthapus)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btreset)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btkembali)))))
                        .addGap(17, 17, 17))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 569, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tfpeminjam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(tftanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cobarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bttambah)
                    .addComponent(btedit)
                    .addComponent(bthapus)
                    .addComponent(btreset)
                    .addComponent(btkembali))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(59, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tbpinjamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbpinjamMouseClicked
       
     int baris = tbpinjam.getSelectedRow();

    if(baris > -1){

        tfid.setText(
                tbpinjam.getValueAt(baris, 0).toString()
        );

        tfpeminjam.setText(
                tbpinjam.getValueAt(baris, 1).toString()
        );

        tftanggal.setText(
                tbpinjam.getValueAt(baris, 2).toString()
        );
    }     // TODO add your handling code here:
    }//GEN-LAST:event_tbpinjamMouseClicked

    private void bttambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttambahActionPerformed
        if(tfpeminjam.getText().trim().isEmpty()){

        JOptionPane.showMessageDialog(
                null,
                "Nama peminjam tidak boleh kosong!"
        );

        return;
    }

    ModelPinjam mp = new ModelPinjam();

    mp.setPeminjam(
            tfpeminjam.getText()
    );

    mp.setTanggal(
            tftanggal.getText()
    );

    mp.setId_barang(
            Integer.parseInt(
                    cobarang.getSelectedItem().toString()
            )
    );

    controller.tambah(mp);

    tampilkanData();
    resetForm(); // TODO add your handling code here:
    }//GEN-LAST:event_bttambahActionPerformed

    private void bteditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bteditActionPerformed
     
    if(tfid.getText().isEmpty()){

        JOptionPane.showMessageDialog(
                null,
                "Pilih data terlebih dahulu!"
        );

        return;
    }

    ModelPinjam mp = new ModelPinjam();

    mp.setId_pinjam(
            Integer.parseInt(
                    tfid.getText()
            )
    );

    mp.setPeminjam(
            tfpeminjam.getText()
    );

    mp.setTanggal(
            tftanggal.getText()
    );

    mp.setId_barang(
            Integer.parseInt(
                    cobarang.getSelectedItem().toString()
            )
    );

    controller.edit(mp);

    tampilkanData();
    resetForm();  // TODO add your handling code here:
    }//GEN-LAST:event_bteditActionPerformed

    private void bthapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bthapusActionPerformed
         if(tfid.getText().isEmpty()){

        JOptionPane.showMessageDialog(
                null,
                "Pilih data terlebih dahulu!"
        );

        return;
    }

    int jawab = JOptionPane.showConfirmDialog(
            null,
            "Yakin hapus data?",
            "Konfirmasi",
            JOptionPane.YES_NO_OPTION
    );

    if(jawab == JOptionPane.YES_OPTION){

        controller.hapus(
                tfid.getText()
        );

        tampilkanData();
        resetForm();
    }   // TODO add your handling code here:
    }//GEN-LAST:event_bthapusActionPerformed

    private void btresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btresetActionPerformed
        resetForm();        // TODO add your handling code here:
    }//GEN-LAST:event_btresetActionPerformed

    private void btkembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btkembaliActionPerformed
        int konfirmasi = JOptionPane.showConfirmDialog(null,
            "Yakin ingin keluar?", "Konfirmasi",
            JOptionPane.YES_NO_OPTION);

        if (konfirmasi == JOptionPane.YES_OPTION) {
            new FormUtama().setVisible(true);
            this.dispose();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_btkembaliActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FormPinjam().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btedit;
    private javax.swing.JButton bthapus;
    private javax.swing.JButton btkembali;
    private javax.swing.JButton btreset;
    private javax.swing.JButton bttambah;
    private javax.swing.JComboBox<String> cobarang;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbpinjam;
    private javax.swing.JTextField tfid;
    private javax.swing.JTextField tfpeminjam;
    private javax.swing.JTextField tftanggal;
    // End of variables declaration//GEN-END:variables
}
