/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Form;
import Controller.ControllerBarang;
import Model.ModelBarang;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Nanda
 */
public class FormBarang extends javax.swing.JFrame {
    
    ControllerBarang controller = new ControllerBarang();
DefaultTableModel model = new DefaultTableModel();
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormBarang.class.getName());

    /**
     * Creates new form FormBarang
     */
    public FormBarang() {
    initComponents();

    model.addColumn("ID Barang");
    model.addColumn("Nama Barang");
    model.addColumn("Stok");

    tbbarang.setModel(model);

    tampilkanData();

    tfid.setEnabled(false);
}
    
    private void tampilkanData() {
    controller.tampil(model);
}
    
    private void resetForm() {
    tfid.setText("");
    tfnama.setText("");
    tfstok.setText("");

    tfnama.requestFocus();
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbbarang = new javax.swing.JTable();
        bttambah = new javax.swing.JButton();
        btreset = new javax.swing.JButton();
        btkembali = new javax.swing.JButton();
        tfstok = new javax.swing.JTextField();
        tfnama = new javax.swing.JTextField();
        tfid = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btedit = new javax.swing.JButton();
        bthapus = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tbbarang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID Barang", "Nama", "Stok"
            }
        ));
        tbbarang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbbarangMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbbarang);

        bttambah.setText("Tambah");
        bttambah.addActionListener(this::bttambahActionPerformed);

        btreset.setText("Reset");
        btreset.addActionListener(this::btresetActionPerformed);

        btkembali.setText("Kembali");
        btkembali.addActionListener(this::btkembaliActionPerformed);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("FORM BARANG");

        jLabel2.setText("ID Barang");

        jLabel3.setText("Nama");

        jLabel4.setText("Stok");

        btedit.setText("Edit");
        btedit.addActionListener(this::bteditActionPerformed);

        bthapus.setText("Hapus");
        bthapus.addActionListener(this::bthapusActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(243, 243, 243)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel4))
                                        .addGap(28, 28, 28)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(tfid, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)
                                            .addComponent(tfnama)
                                            .addComponent(tfstok)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(bttambah)
                                        .addGap(15, 15, 15)
                                        .addComponent(btedit)
                                        .addGap(15, 15, 15)
                                        .addComponent(bthapus)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btreset)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btkembali)))))
                        .addGap(17, 17, 17))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 557, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tfnama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(tfstok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bttambah)
                    .addComponent(btreset)
                    .addComponent(btkembali)
                    .addComponent(btedit)
                    .addComponent(bthapus))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tbbarangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbbarangMouseClicked
       int baris = tbbarang.getSelectedRow();

    if(baris > -1){

        tfid.setText(
                tbbarang.getValueAt(baris, 0).toString()
        );

        tfnama.setText(
                tbbarang.getValueAt(baris, 1).toString()
        );

        tfstok.setText(
                tbbarang.getValueAt(baris, 2).toString()
        );
    }     // TODO add your handling code here:
    }//GEN-LAST:event_tbbarangMouseClicked

    private void bttambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttambahActionPerformed
        // Validasi nama tidak boleh kosong
        if(tfnama.getText().trim().isEmpty()){
        JOptionPane.showMessageDialog(
                null,
                "Nama Barang Tidak Boleh Kosong!"
        );
        return;
    }

    ModelBarang mb = new ModelBarang();

    mb.setNama_barang(
            tfnama.getText()
    );

    mb.setStok(
            Integer.parseInt(
                    tfstok.getText()
            )
    );

    controller.tambah(mb);

    tampilkanData();
    resetForm();    // TODO add your handling code here:
    }//GEN-LAST:event_bttambahActionPerformed

    private void btresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btresetActionPerformed
          resetForm();        // TODO add your handling code here:
    }//GEN-LAST:event_btresetActionPerformed

    private void btkembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btkembaliActionPerformed
        int konfirmasi = JOptionPane.showConfirmDialog(null,
            "Yakin ingin keluar?", "Konfirmasi",
            JOptionPane.YES_NO_OPTION);

        if (konfirmasi == JOptionPane.YES_OPTION) {
            new FormUtama().setVisible(true);
            this.dispose();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_btkembaliActionPerformed

    private void bteditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bteditActionPerformed
     if(tfid.getText().isEmpty()){
        JOptionPane.showMessageDialog(
                null,
                "Pilih data terlebih dahulu!"
        );
        return;
    }

    ModelBarang mb = new ModelBarang();

    mb.setId_barang(
            Integer.parseInt(
                    tfid.getText()
            )
    );

    mb.setNama_barang(
            tfnama.getText()
    );

    mb.setStok(
            Integer.parseInt(
                    tfstok.getText()
            )
    );

    controller.edit(mb);

    tampilkanData();
    resetForm();        // TODO add your handling code here:
    }//GEN-LAST:event_bteditActionPerformed

    private void bthapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bthapusActionPerformed
        if(tfid.getText().isEmpty()){

        JOptionPane.showMessageDialog(
                null,
                "Pilih data terlebih dahulu!"
        );

        return;
    }

    int jawab = JOptionPane.showConfirmDialog(
            null,
            "Yakin hapus data?",
            "Konfirmasi",
            JOptionPane.YES_NO_OPTION
    );

    if(jawab == JOptionPane.YES_OPTION){

        controller.hapus(
                tfid.getText()
        );

        tampilkanData();
        resetForm();
    }        // TODO add your handling code here:
    }//GEN-LAST:event_bthapusActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FormBarang().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btedit;
    private javax.swing.JButton bthapus;
    private javax.swing.JButton btkembali;
    private javax.swing.JButton btreset;
    private javax.swing.JButton bttambah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbbarang;
    private javax.swing.JTextField tfid;
    private javax.swing.JTextField tfnama;
    private javax.swing.JTextField tfstok;
    // End of variables declaration//GEN-END:variables
}
